goliatjs/erp/urls.py
from django.urls import path

from erp.views.categoria.vistaCategoria import *
from erp.views.cliente.vistaCliente import *


from erp.views.dashboard.views import DashboardView
#from erp.views.producto.views import *
from erp.views.producto.vistaProducto import *
from erp.views.proveedor.vistaProveedor import listarProveedor, agregarProveedor, ProveedorDeleteView
#from erp.views.venta.views import *
from erp.views.venta.vistaVenta import *
#from erp.views.venta.views import *
from erp.views.compra.vistaCompra import *
#from erp.views.compra.views import *

from erp.views.tests.views import TestView

app_name = 'erp'

urlpatterns = [
    # categoria
    path('categoria/list/', listarCategoria.as_view(), name='category_list'),
    path('categoria/add/', crearCategoria.as_view(), name='category_create'),
    path('categoria/editar/<int:pk>/',editarCategoria.as_view(), name='editar_Categoria'),
    path('categoria/eliminar/<int:pk>/',eliminarCategoria.as_view(), name='eliminar_Categoria'),

    # proveedor
    path('listar/proveedor/', listarProveedor.as_view(), name='listar_proveedor'),
    path('agregar/proveedor/', agregarProveedor.as_view(), name='agregar_proveedor'),
    path('eliminar/proveedor/<int:pk>/', ProveedorDeleteView.as_view(), name='proveedor_elminnar'),

    # cliente
    path('listar/cliente/', listarCliente.as_view(), name='listar_Cliente'),
    path('agregar/cliente/', agregarCliente.as_view(), name='agregar_clente'),
    path('editar/cliente/<int:pk>/', editarCliente.as_view(), name='editar_cliente'),
    path('eliminar/cliente/<int:pk>/', eliminarCliente.as_view(), name='eliminar_cliente'),


    # producto
    path('producto/list/', listarProducto.as_view(), name='product_list'),
    path('producto/add/', agregarProducto.as_view(), name='product_create'),
    path('producto/editar/<int:pk>/', actualizarProducto.as_view(), name='editarProducto'),
    path('producto/eliminar/<int:pk>/', eliminarProducto.as_view(), name='eliminarProducto'),

    # home
    path('dashboard/', DashboardView.as_view(), name='dashboard'),

    # test
    path('test/', TestView.as_view(), name='test'),
    # venta

    # compras
    path('Listar/compra/', listarCompra.as_view(), name='listar_compras'),
    path('Agregar/compra/', CrearCompra.as_view(), name='crear_compras'),
    path('compra/borrarCompra/<int:pk>/', eliminarCompra.as_view(), name='borrar_compra'),
    path('compra/editarComp/<int:pk>/', EditarCompra.as_view(), name='editar_compra'),

    # ventas
    path('Listar/venta/', listarVentas.as_view(), name='listar_ventas'),
    path('crear/venta/', crearVentas.as_view(), name='crear_venta'),
    path('eliminar/venta/<int:pk>/', eliminarVentas.as_view(), name='eliminar_venta'),
    path('editar/venta/<int:pk>/', editarVentas.as_view(), name='editar_venta'),
]

goliatjs/goliatjs/urls.py
from django.contrib import admin
from django.urls import path, include
from core.homepage.views import IndexView
from core.login.views import *

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('login/', include('core.login.urls')),
    path('admin/', admin.site.urls),
    path('erp/', include('erp.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

goliatjs/templates/vtc/body.html
{% extends 'home.html' %}
{% block body %}
    <body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
        <!-- Header -->
        {% include 'vtc/header.html' %}
        <!-- Sidebar -->
        {% include 'vtc/sidebar.html' %}
        <!-- Content -->
        <div class="content-wrapper">
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark"> Bienvenido <small>{{ request.user.get_full_name }}</small></h1>
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="{% url 'erp:dashboard' %}">Home</a></li>
                                <li class="breadcrumb-item"><a href="{{ list_url }}">{{ entity }}</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="container-fluid">
                    {% block content %}

                    {% endblock %}
                </div>
            </div>
        </div>
        <!-- Footer -->
        {% include 'footer.html' %}
    </div>
    <!-- Block javascript -->
    {% block javascript %}

    {% endblock %}
    <script>
        {% if messages %}
            var html = '<p>';
            {% for message in messages %}
                html += '{{ message }}<br>';
            {% endfor %}
            html += '</p>';
            Swal.fire({
                title: 'Error!',
                html: html,
                icon: 'error'
            });
        {% endif %}
    </script>
    </body>
{% endblock %}

goliatjs/templates/vtc/header.html
<nav class="main-header navbar navbar-expand navbar-dark navbar-primary">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="{% url 'erp:dashboard' %}" class="nav-link">Home</a>
        </li>
    </ul>
    <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="fas fa-users-cog"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                    <span class="dropdown-header" style="font-size: 12px;">
                        Sú último acceso fue {{ request.user.last_login }}
                    </span>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-edit mr-2"></i> Editar perfil
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-lock mr-2"></i> Editar password
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">
                    <p>Este sistema te permitira realizar diferentes actividades</p>
                </a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">
                <i class="fas fa-power-off" aria-hidden="true"></i>
            </a>
        </li>
    </ul>
</nav>

goliatjs/templates/vtc/sidebar.html
{% load static %}
<aside class="main-sidebar sidebar-light-primary elevation-4">
    <a href="{% url 'erp:dashboard' %}" class="brand-link">
        <img src="{% static 'img/logo.png' %}"
             alt="AdminLTE Logo"
             class="brand-image img-circle elevation-3"
             style="opacity: .8">
        <span class="brand-text font-weight-light">Hades</span>
    </a>
    <div class="sidebar">
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{{ request.user.get_image }}" class="img-circle" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">{{ request.user.username }}</a>
            </div>
        </div>
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-header">Mantenimientos</li>
                <li class="nav-item">
                    <a href="{% url 'erp:category_list' %}" class="nav-link">
                        <i class="nav-icon fas fa-truck-loading"></i>
                        <p>
                            Categorías
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'erp:product_list' %}" class="nav-link">
                        <i class="nav-icon fas fa-boxes"></i>
                        <p>
                            Productos
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'erp:listar_Cliente' %}" class="nav-link">
                        <i class="nav-icon fas fa-users"></i>
                        <p>
                            Clientes
                        </p>
                    </a>
                </li>
                 <li class="nav-item">
                    <a href="{% url 'erp:listar_proveedor' %}" class="nav-link">
                        <i class="nav-icon fas fa-users"></i>
                        <p>
                            Proveedores
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'erp:listar_compras'%}" class="nav-link">
                        <i class="fas fa-shopping-basket"></i>
                        <p>
                            Compras
                        </p>
                    </a>

                </li>
                <li class="nav-item">
                    <a href="{% url 'erp:listar_ventas'%}" class="nav-link">
                        <i class="nav-icon fas fa-shopping-cart"></i>
                        <p>
                            Ventas
                        </p>
                    </a>
                </li>

            </ul>
        </nav>
    </div>
</aside>